### PR TITLE
Play and Cursor Head

### PR DESCRIPTION
**Pull request by danielyaa5**
Created a Play Head and also a Cursor Head. 

Updated context menu to be its own component.

### CODE REVIEW

**Comment by asg0451** [comment]
accidentally deleted and closed..... nothing is fucked here dude

**Review by asg0451 — APPROVED** [review]
@danielyaa5 good, but I did notice one small bug I'd like you to fix before you merge. When the height of the viewport is less than that of the Table, the cursor and play head are the length of the viewport, not the Table, so if you scroll down it won't display on the whole Table. Kind of an edge case but i ran into it immediately cause devtools.

**Comment by danielyaa5** [comment]
@asg0451 nice catch, take a look at my updates and merge resolution before I merge.

**Comment by danielyaa5** [comment]
@asg0451 updated for reals now, just make sure it works on your computer before i merge

**Review by asg0451 — CHANGES_REQUESTED** [review]
you've introduced a new bug. try moving a clip down into another track. everything gets all fucky. no good :(

**Review by asg0451 — APPROVED** [review]

**Pull request merged**
